### ISSUE TITLE
Missing "Rating in activity" option in Statistics for learning plans

### ISSUE THREAD

**Issue by phildespres** [StudiUM/moodle-report_lpmonitoring#10]
Hi,
just had a demo of the plugin by UdeM staff and I was able to see a "Rating in activity" option in the "Statistics for learning plans". On my install (last version 1.4 on Moodle 3.9) I can only see "Final rating" and "Rating in course options". Am I missing something?
Thanks!

**Comment by taboubi** [comment]
Hi,
because internally we have developed a feature that allows us to rate competencies at the activity level, so lpmonitoring use $iscmcompetencygradingenabled to check if this feature is activated and tries to display these ratings. So you can't have these ratings in the report unless the feature of rating at course module level exist.
If you are interessted in this feature you have to use those plugins: 
https://moodle.org/plugins/report_cmcompetency
https://moodle.org/plugins/tool_cmcompetency
And then set the var $iscmcompetencygradingenabled to TRUE.

**Comment by phildespres** [comment]
Thanks. I  have installed the modules. Where should I set this variable?

**Comment by taboubi** [comment]
here:

https://github.com/StudiUM/moodle-report_lpmonitoring/blob/master/classes/api.php#L64
